Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.box = "centos/7"
    master.vm.network "private_network", ip: "192.168.55.20"
    master.vm.hostname = "master"
  end

  config.vm.define "target1" do |target1|
    target1.vm.hostname = "target1"
    target1.vm.box = "centos/7"
    target1.vm.network "private_network", ip: "192.168.55.21"
    target1.vm.hostname = "target1"
  end

  config.vm.define "target2" do |target2|
    target2.vm.hostname = "target2"
    target2.vm.box = "centos/7"
    target2.vm.network "private_network", ip: "192.168.55.22"
    target2.vm.hostname = "target2"
  end    

end