Vagrant.configure("2") do |config|
  config.vm.provision "shell",
    inline: "sudo sed -i 's/^#PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config && sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config && systemctl restart sshd"

 # Deploy Application with Shell Script
  # config.vm.provision :shell, path: "project-deploy.sh"

  config.vm.define "lamp" do |target3|
    target3.vm.hostname = "lamp"
    target3.vm.box = "centos/7"
    target3.vm.network "private_network", ip: "192.168.55.23"

    # Deploy App with Ansible 
    target3.vm.provision :ansible do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = 'project-deploy1.yml'
      ansible.become = true
    end

  end

end